# Generated by Django 4.0.1 on 2022-04-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_answer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=800),
        ),
    ]
