# Generated by Django 4.0.1 on 2022-03-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_remove_about_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
