# Generated by Django 4.0.1 on 2022-04-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('plan', models.CharField(max_length=200)),
            ],
        ),
    ]
