# Generated by Django 4.0.1 on 2022-04-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_bounty_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto_logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('svg', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
