# Generated by Django 4.0.1 on 2022-04-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_crypto_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto_logo',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
