# Generated by Django 4.0.1 on 2022-04-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='testimony',
            field=models.TextField(max_length=300),
        ),
    ]
