# Generated by Django 4.0.1 on 2022-04-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_alter_feedback_testimony'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='title',
        ),
    ]
