# Generated by Django 4.0.1 on 2022-04-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_remove_plan_plan_remove_plan_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='Duration',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='Referral',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_deposit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='min_deposit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='roi',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
