# Generated by Django 4.0.1 on 2022-04-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0011_plan_duration_plan_referral_plan_max_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(default='h', max_length=200),
            preserve_default=False,
        ),
    ]
