# Generated by Django 4.0.1 on 2022-04-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0012_plan_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='Duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
