# Generated by Django 4.0.1 on 2022-04-08 16:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0013_alter_plan_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='background_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='heading',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bounty',
            name='my_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='sub_heading',
            field=models.CharField(default=45, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.CharField(max_length=300)),
                ('reward', models.CharField(max_length=200)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.bounty')),
            ],
        ),
    ]
