# Generated by Django 4.0.1 on 2022-03-21 14:39

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_dashboard_comparator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='pending_deposit',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(20)], verbose_name='Deposit Amount'),
        ),
    ]
