# Generated by Django 4.0.1 on 2022-05-05 15:25

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_dashboard_wallet_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='notify_user',
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='approved_deposit',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=19, validators=[djmoney.models.validators.MinMoneyValidator(1)], verbose_name='Approved Deposit'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='approved_withdrawal',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=19, validators=[djmoney.models.validators.MinMoneyValidator(1)], verbose_name='Aprroved_withdrawal'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=19, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='comparator',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('1.0'), default_currency='USD', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(1), djmoney.models.validators.MaxMoneyValidator(1)], verbose_name='comparator'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='earnings',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(1)]),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='pending_withdrawal',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(1)], verbose_name='Withdrawal Amount'),
        ),
    ]
