# Generated by Django 4.0.1 on 2022-06-21 13:23

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_dashboard_notify_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='earnings_currency',
            new_name='profit_currency',
        ),
        migrations.RemoveField(
            model_name='address',
            name='bnb',
        ),
        migrations.RemoveField(
            model_name='address',
            name='btc',
        ),
        migrations.RemoveField(
            model_name='address',
            name='eth',
        ),
        migrations.RemoveField(
            model_name='address',
            name='usdt',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='earnings',
        ),
        migrations.AddField(
            model_name='address',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='address',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='address',
            name='token',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Wallet Address'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='profit',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14, null=True, validators=[djmoney.models.validators.MinMoneyValidator(1)], verbose_name='Profit'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='tokens',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether'), ('BNB', 'BNB')], default='BTC', max_length=4),
        ),
    ]
