# Generated by Django 4.0.5 on 2022-08-17 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0009_rename_earnings_currency_dashboard_profit_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='id',
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='accountUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='profit_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD Dollar')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD Dollar')], default='USD', editable=False, max_length=3, null=True),
        ),
    ]
